language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 20.0
  - 21.0
install:
  - mix local.hex --force
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
