language: elixir
elixir:
  - 1.0
  - 1.1.0
  - 1.2
otp_release:
  - 18.0
install:
  - mix local.hex --force
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
